{
 "title": "Air Quality",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Current temperature indoors (avg)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"aqm\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"air_quality\" and\r\n    r._field == \"temperature\"\r\n  )"
    }
   ]
  },
  {
   "title": "Indoor Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"aqm\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"air_quality\" and\r\n    r._field == \"temperature\"\r\n  )"
    }
   ]
  },
  {
   "title": "Current relative humidity indoors (avg)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"aqm\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"air_quality\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\" and r.sensor != \"DHT22\")"
    }
   ]
  },
  {
   "title": "Indoor Relative humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"aqm\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"air_quality\" and\r\n    r._field == \"humidity\"\r\n  )"
    }
   ]
  },
  {
   "title": "Indoor and outdoor temperature",
   "type": "timeseries",
   "description": "SMHI weather station ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"aqm\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"air_quality\" and\r\n    r._field == \"temperature\"\r\n  )"
    },
    {
     "columns": [
      { "selector": "value", "text": "SMHI Kroppefjell", "type": "number" },
      { "selector": "date", "text": "Time", "type": "timestamp_epoch" }
     ],
     "root_selector": "value",
     "source": "url",
     "type": "json",
     "url": "/api/version/1.0/parameter/1/station/82360/period/latest-day/data.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Indoor and outdoor RH",
   "type": "timeseries",
   "description": "SMHI weather station ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"aqm\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"air_quality\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\" and r.sensor != \"DHT22\")"
    },
    {
     "columns": [
      { "selector": "value", "text": "SMHI Kroppefjell", "type": "number" },
      { "selector": "date", "text": "Time", "type": "timestamp_epoch" }
     ],
     "root_selector": "value",
     "source": "url",
     "type": "json",
     "url": "/api/version/1.0/parameter/6/station/82360/period/latest-day/data.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}