# compose.yaml
services:
  influxdb2:
    image: influxdb:2.7.10
    ports:
      - 28086:8086
      - 28088:8088
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: aqm
      DOCKER_INFLUXDB_INIT_BUCKET: aqm
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - ./data:/var/lib/influxdb2 # change ./data to a location where you want persisted data to be stored on host machine
      - ./influx-configs:/etc/influxdb2/

# create the below .env files with the content you wish
secrets:
  influxdb2-admin-username:
    file: .env.influxdb2-admin-username
  influxdb2-admin-password:
    file: .env.influxdb2-admin-password
  influxdb2-admin-token:
    file: .env.influxdb2-admin-token